// Generated by gencpp from file cs_merge_msgs/getTransformRequest.msg
// DO NOT EDIT!


#ifndef CS_MERGE_MSGS_MESSAGE_GETTRANSFORMREQUEST_H
#define CS_MERGE_MSGS_MESSAGE_GETTRANSFORMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/OccupancyGrid.h>
#include <nav_msgs/OccupancyGrid.h>

namespace cs_merge_msgs
{
template <class ContainerAllocator>
struct getTransformRequest_
{
  typedef getTransformRequest_<ContainerAllocator> Type;

  getTransformRequest_()
    : map_one()
    , map_two()  {
    }
  getTransformRequest_(const ContainerAllocator& _alloc)
    : map_one(_alloc)
    , map_two(_alloc)  {
    }



   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _map_one_type;
  _map_one_type map_one;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _map_two_type;
  _map_two_type map_two;




  typedef boost::shared_ptr< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> const> ConstPtr;

}; // struct getTransformRequest_

typedef ::cs_merge_msgs::getTransformRequest_<std::allocator<void> > getTransformRequest;

typedef boost::shared_ptr< ::cs_merge_msgs::getTransformRequest > getTransformRequestPtr;
typedef boost::shared_ptr< ::cs_merge_msgs::getTransformRequest const> getTransformRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cs_merge_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'cs_merge_msgs': ['/home/christian/catkin_ws/src/cs_merge/cs_merge_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ada89033b0dcc741eab33caf37ae322e";
  }

  static const char* value(const ::cs_merge_msgs::getTransformRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xada89033b0dcc741ULL;
  static const uint64_t static_value2 = 0xeab33caf37ae322eULL;
};

template<class ContainerAllocator>
struct DataType< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cs_merge_msgs/getTransformRequest";
  }

  static const char* value(const ::cs_merge_msgs::getTransformRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
nav_msgs/OccupancyGrid map_one\n\
nav_msgs/OccupancyGrid map_two\n\
\n\
================================================================================\n\
MSG: nav_msgs/OccupancyGrid\n\
# This represents a 2-D grid map, in which each cell represents the probability of\n\
# occupancy.\n\
\n\
Header header \n\
\n\
#MetaData for the map\n\
MapMetaData info\n\
\n\
# The map data, in row-major order, starting with (0,0).  Occupancy\n\
# probabilities are in the range [0,100].  Unknown is -1.\n\
int8[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::cs_merge_msgs::getTransformRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_one);
      stream.next(m.map_two);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct getTransformRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cs_merge_msgs::getTransformRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cs_merge_msgs::getTransformRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_one: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.map_one);
    s << indent << "map_two: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.map_two);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CS_MERGE_MSGS_MESSAGE_GETTRANSFORMREQUEST_H
