// Generated by gencpp from file cs_merge_msgs/getTransform.msg
// DO NOT EDIT!


#ifndef CS_MERGE_MSGS_MESSAGE_GETTRANSFORM_H
#define CS_MERGE_MSGS_MESSAGE_GETTRANSFORM_H

#include <ros/service_traits.h>


#include <cs_merge_msgs/getTransformRequest.h>
#include <cs_merge_msgs/getTransformResponse.h>


namespace cs_merge_msgs
{

struct getTransform
{

typedef getTransformRequest Request;
typedef getTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getTransform
} // namespace cs_merge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cs_merge_msgs::getTransform > {
  static const char* value()
  {
    return "33cf49a04ac4ccb9206baa236692fb49";
  }

  static const char* value(const ::cs_merge_msgs::getTransform&) { return value(); }
};

template<>
struct DataType< ::cs_merge_msgs::getTransform > {
  static const char* value()
  {
    return "cs_merge_msgs/getTransform";
  }

  static const char* value(const ::cs_merge_msgs::getTransform&) { return value(); }
};


// service_traits::MD5Sum< ::cs_merge_msgs::getTransformRequest> should match 
// service_traits::MD5Sum< ::cs_merge_msgs::getTransform > 
template<>
struct MD5Sum< ::cs_merge_msgs::getTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cs_merge_msgs::getTransform >::value();
  }
  static const char* value(const ::cs_merge_msgs::getTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs_merge_msgs::getTransformRequest> should match 
// service_traits::DataType< ::cs_merge_msgs::getTransform > 
template<>
struct DataType< ::cs_merge_msgs::getTransformRequest>
{
  static const char* value()
  {
    return DataType< ::cs_merge_msgs::getTransform >::value();
  }
  static const char* value(const ::cs_merge_msgs::getTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cs_merge_msgs::getTransformResponse> should match 
// service_traits::MD5Sum< ::cs_merge_msgs::getTransform > 
template<>
struct MD5Sum< ::cs_merge_msgs::getTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cs_merge_msgs::getTransform >::value();
  }
  static const char* value(const ::cs_merge_msgs::getTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs_merge_msgs::getTransformResponse> should match 
// service_traits::DataType< ::cs_merge_msgs::getTransform > 
template<>
struct DataType< ::cs_merge_msgs::getTransformResponse>
{
  static const char* value()
  {
    return DataType< ::cs_merge_msgs::getTransform >::value();
  }
  static const char* value(const ::cs_merge_msgs::getTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CS_MERGE_MSGS_MESSAGE_GETTRANSFORM_H
