// Generated by gencpp from file cs_merge_msgs/getWorldRequest.msg
// DO NOT EDIT!


#ifndef CS_MERGE_MSGS_MESSAGE_GETWORLDREQUEST_H
#define CS_MERGE_MSGS_MESSAGE_GETWORLDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cs_merge_msgs
{
template <class ContainerAllocator>
struct getWorldRequest_
{
  typedef getWorldRequest_<ContainerAllocator> Type;

  getWorldRequest_()
    {
    }
  getWorldRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> const> ConstPtr;

}; // struct getWorldRequest_

typedef ::cs_merge_msgs::getWorldRequest_<std::allocator<void> > getWorldRequest;

typedef boost::shared_ptr< ::cs_merge_msgs::getWorldRequest > getWorldRequestPtr;
typedef boost::shared_ptr< ::cs_merge_msgs::getWorldRequest const> getWorldRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cs_merge_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'cs_merge_msgs': ['/home/christian/catkin_ws/src/cs_merge/cs_merge_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cs_merge_msgs::getWorldRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cs_merge_msgs/getWorldRequest";
  }

  static const char* value(const ::cs_merge_msgs::getWorldRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::cs_merge_msgs::getWorldRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct getWorldRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cs_merge_msgs::getWorldRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cs_merge_msgs::getWorldRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CS_MERGE_MSGS_MESSAGE_GETWORLDREQUEST_H
