// Generated by gencpp from file cs_merge_msgs/getWorld.msg
// DO NOT EDIT!


#ifndef CS_MERGE_MSGS_MESSAGE_GETWORLD_H
#define CS_MERGE_MSGS_MESSAGE_GETWORLD_H

#include <ros/service_traits.h>


#include <cs_merge_msgs/getWorldRequest.h>
#include <cs_merge_msgs/getWorldResponse.h>


namespace cs_merge_msgs
{

struct getWorld
{

typedef getWorldRequest Request;
typedef getWorldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getWorld
} // namespace cs_merge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cs_merge_msgs::getWorld > {
  static const char* value()
  {
    return "a57cc86655fe712508fa4becba72db19";
  }

  static const char* value(const ::cs_merge_msgs::getWorld&) { return value(); }
};

template<>
struct DataType< ::cs_merge_msgs::getWorld > {
  static const char* value()
  {
    return "cs_merge_msgs/getWorld";
  }

  static const char* value(const ::cs_merge_msgs::getWorld&) { return value(); }
};


// service_traits::MD5Sum< ::cs_merge_msgs::getWorldRequest> should match 
// service_traits::MD5Sum< ::cs_merge_msgs::getWorld > 
template<>
struct MD5Sum< ::cs_merge_msgs::getWorldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cs_merge_msgs::getWorld >::value();
  }
  static const char* value(const ::cs_merge_msgs::getWorldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs_merge_msgs::getWorldRequest> should match 
// service_traits::DataType< ::cs_merge_msgs::getWorld > 
template<>
struct DataType< ::cs_merge_msgs::getWorldRequest>
{
  static const char* value()
  {
    return DataType< ::cs_merge_msgs::getWorld >::value();
  }
  static const char* value(const ::cs_merge_msgs::getWorldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cs_merge_msgs::getWorldResponse> should match 
// service_traits::MD5Sum< ::cs_merge_msgs::getWorld > 
template<>
struct MD5Sum< ::cs_merge_msgs::getWorldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cs_merge_msgs::getWorld >::value();
  }
  static const char* value(const ::cs_merge_msgs::getWorldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs_merge_msgs::getWorldResponse> should match 
// service_traits::DataType< ::cs_merge_msgs::getWorld > 
template<>
struct DataType< ::cs_merge_msgs::getWorldResponse>
{
  static const char* value()
  {
    return DataType< ::cs_merge_msgs::getWorld >::value();
  }
  static const char* value(const ::cs_merge_msgs::getWorldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CS_MERGE_MSGS_MESSAGE_GETWORLD_H
